### ISSUE TITLE
Redirect old links to the new

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#190]
- [x] old links targeting elvis.tenders.exposed/whatever should now be point towards tenders.exposed/whatever
- [ ] after #149 is done (blocking issue), old links from the old routes should point to the new ones

**Comment by zufanka** [comment]
This blocking issue is closed already

**Comment by nightsh** [comment]
yes, it is. I was just thinking, given project's current popularity, that this is a non issue actually. What do you think? :smile:

**Comment by georgiana-b** [comment]
@nightsh Does this mean we also have to change the host for [URLs in backend sent emails](https://github.com/tenders-exposed/elvis-backend/blob/master/config/environments/production.rb#L4)?

**Comment by zufanka** [comment]
Oh yes :) just maybe redirect elvis.tenders.exposed to tenders.exposed ?

On May 26, 2017 2:19 PM, "georgiana-b" <notifications@github.com> wrote:

@nightsh <https://github.com/nightsh> Does this mean we also have to change
the host for URLs in backend sent emails
<https://github.com/tenders-exposed/elvis-backend/blob/master/config/environments/production.rb#L4>
?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tenders-exposed/elvis-ember/issues/190#issuecomment-304269055>,
or mute the thread

**Comment by nightsh** [comment]
Well, turns out I fixed it a while ago, if anyone else sees otherwise please feel free to reopen this. Closing now.
