### ISSUE TITLE
Big pink blobs in the network detail views

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#242]
![image](https://user-images.githubusercontent.com/2411066/27588719-5edd532e-5b49-11e7-81d5-30e2a2fd59c1.png)

**Comment by chutko** [comment]
best solution will be to use more specific style definitions and class names. 
instead of `.procurer { // style here }` use rather `.supplier-detail-view { .tab-procurers { // same styles here } }`

i will also rename the `.relationship, .supplier` and `.procurer` general components so their names correspont with what they are displaying: `relationship-icon, .supplier-icon, .procurer-icon`

**Comment by chutko** [comment]
solved in #256
