### ISSUE TITLE
Frontend of the new Query Builder

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#253]
redesign / rebuild the query builder to improve UX and prepare it for company centric networks. we do not yet have exact solution although we have some points which emerged from the discussion on the topic:

1. query builder will be treated as a wizard, split into few sections
2. next approaching version of the wizard should be dead simple - we will use basic components of materialize to split contents into steps (tabs or accordion), showing everything in single view
3. the whole HTML of the query builder will be generated into DOM. wizard functionality will be delivered by styling and some javascript. 
4. CPV selector will be a single step of this wizard. the whole cpv tree could be displayed right on - without any need to open a modal
5. to discuss: CPV selector could initially be just a dropdown displaying just the first level of the CPV tree. then a button for more specific selection opening current CPV modal. still there is a question how selected CPVs should look (if more specific selection is used)

**Comment by chutko** [comment]
@nightsh basic markup for the query builder is in the branch `feat/query-builder-wizard`. it also contains some comments describing desired functionality. i will improve the design once real data is displayed in there. 

also, there is one idea: is it possible to have single select containing countries and companies?

**Comment by nightsh** [comment]
Replying it backwards :) I'm not sure about the single select. In our case, we get the CPVs, or companies, according to the years/countries selected.

It is however possible to get the companies without passing any other parameters, it would just be a much heavier search on the index, not sure how this would impact performance. Maybe not much now, but if we'd have *all* the countries, imagine instead of looking through companies in 2-3 countries we're doing an autocomplete based on all the companies from all the countries. Not to mention false positives (different companies with identical name between countries, e.g. "ABC COM", which I just made up but I'm pretty sure it exists multiple times).

So I would advise for keeping as many filters as we can **before** touching the CPV selector / ocmpanies drop down. This way we would be able to narrow down as much as we can so we'd leave a smaller data set to go through in the last step.

Now, on to the first thing, I'll get on to do it in a few days, as I'm a bit swamped & stuck right now. But you'll be the first to know when it's up for testing somewhere :)

**Comment by nightsh** [comment]
@georgiana-b any thoughts on this? ☝️

**Comment by chutko** [comment]
i have improved the styling today:
- created separate .wizard component with 3 states for .wizard-step: .disabled, .current, .completed
- fancy-styled the ember-select-guru
- improved various form/input styles when combined with other components
- have put various TODOs into the comments for @nightsh 

i havent styled the CPV selector yet. that will be the final touch. however, now it looks quite good. now, what needs to be done from you guys is to make it work with real data :)

**Comment by chutko** [comment]
btw dont forget to do some cleanup when this is ready - mostly deleting redundant files which are not used anymore (cpv selector modal)
