### ISSUE TITLE
Human readable CPV tree

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#286]
Create  a human readable CPV tree based on the http://ted.europa.eu/TED/browse/browseByBS.do

![image](https://user-images.githubusercontent.com/2411066/29886565-c8fd2498-8dba-11e7-9125-a393091b5055.png)

- with parents that are not selectable

**Comment by nightsh** [comment]
I'm blocking this, due to the following:

* the TED tree has duplicate subtrees between the human readable parents (i.e. some main codes are found in multiple categories)
* jsTree cannot work with duplicates, we can only specify one parent
  * if we modify jsTree to work with more parents (i.e. duplicate whole subtrees) we might expect hell on tree actions (as we won't have unique IDs anymore) and a bit on query building

Ending with a question:
Is there a way to have a human readable tree without having the root categories overlap?

**Comment by nightsh** [comment]
@zufanka do you have any idea how to unblock this? 🤔

**Comment by nightsh** [comment]
Unblocked following a discussion with everybody: we will keep only single parents (so no duplicates) in a first iteration, then later we will attempt implementing multiple parents into jstree.

**Comment by zufanka** [comment]
@nightsh let's close this issue for now I think. We don't have the time to fuck it up and there is more pressing stuff on our plates. I think we might need to have a better look at this part of the query builder anyway in the future. Agreed?

**Comment by victor-nitu** [comment]
Agreed.

I would like to deploy an old version of elvis with the cpv popup somewhere and ask for ideas, or something... I am feeling completely lost tbh, but we do miss a lot of cpv functionality now (search!) that we could integrate into the design (we have it) if only we'd know how to arrange things in there. We need more feedback on this, I guess.

But I got sidetracked. As far as this issue goes, we close it for now due to multiple historical reasons, and will be reopened once we figure out how the CPV selector should look like :)
