### ISSUE TITLE
Improve Login and Register functionality

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#317]
i have studied how login and registration work now and i would like to propose changes into current functionality. this is quite related to #195, just extends to solution.
here is a brief example of login functionality and template structure (will be the same with register)
![elvis--usecase-login](https://user-images.githubusercontent.com/4135015/31171619-a386839c-a900-11e7-94c8-0b58c5265ae7.jpg)

to achieve this state, we need to: 
1. create actions to display login and registration forms in modals (login modal and register modal).

2. using ember-cli-materialize modal component http://ember-materialize.mike.works/#/modal

3. besides modals, it is desirable to have also static routes for login and register - there needs to be a link available for such an important action in the system so it could be shared amongst users. 

4. login and register forms should be defined as components which can be then included into static route pages and modals

5. create general modal triggering functionality. i love how simple bootstrap modals are - you just need to use proper html markup (target in a data-trigger attribute) to create a modal:
```
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data- target="#exampleModal">  Launch demo modal </button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">modal content here</div>
```
if this is possible in ember, we can maintain consistency in using modals and do not need to create a separate action for every modal.

**Comment by victor-nitu** [comment]
I'm happy to see this issue being tackled. Just in time for our authentication revamping, as it's gonna be redesigned on the backend as well.

So thanks for raising this and putting the effort to investigate potential scenarios. I'll reply on your points below.

---

1. Actions will be created and stored in the same place, route-agnostic (as in, not in routes/controllers, but rather in decoupled components)
2. Yes!
3. This is an issue in itself. We cannot have routes **and** modals at the same time, and not have what we already do. Because routes have their own URLs, but we want this thing to be usable from any route. So we basically need to spawn a login/register component and fire up its templates and actions through triggers and links. Sadly, this means it's either not going to have a link, or we create login/register/etc. separate routes and load their modals as "normal" pages (and hide the nav controls in this case). Does it make sense?
4. Not really included, but rather fired through actions on links and other elements. I already addressed this above ☝️ 
5. We can do that, yes. But we might end up in funny situations if we try too hard to make it an abstract action. We can try raising an issue for it when we have some (working) code to lean it against.

So, shall we try with a component and then attempt creating some static routes as well? Or do you have anything else in mind? Anyone else, ideas? :)

**Comment by victor-nitu** [comment]
Also linking #195 here.

**Comment by chutko** [comment]
3. not sure i understand. for me the solutions im proposing seem like a basic things which any framework (including ember) should be able to do just by using core features (actions/including, whatever). maybe i just expressed that in wrong way. 

to be general, my desire is to have action (click) firing a modal containing a form (on every page) and also having a separate page containing the same form (and same logic). 

also, is it a problem to create a special link for modal? say if we have a route _tenders.exposed/about_ and user clicks on login button in the navbar, the modal appears and route should change to _tenders.exposed/about/login_, is that a problem?

**Comment by chutko** [comment]
okay, i tried to catch it all in the following flowchart:
![elvis--login-register-flowchart](https://user-images.githubusercontent.com/4135015/31546276-e4b48b9c-b022-11e7-8bb4-11a856af02b8.png)

@nightsh @ca1yps0 who shall i assign this to? 

i will start working on HTML/CSS as soon as the templates are ready. the goal of this task is to logically separate markup into few files so the templates can be reused later and the markup code for modals/forms is includable and editable separately. here is the list:
- register form template
- login form template
- register page template - **account/new.hbs** -this one is ready
- password recovery - **account/reset.hbs + account/recover.hbs** these are also ready, not sure if "email was sent to your account" is there.
- login page template
- login modal template (triggered on any route if user is not logged in)

**Comment by victor-nitu** [comment]
Ping @georgiana-b, does it make sense to sync it with backend auth?

**Comment by georgiana-b** [comment]
The specs didn't change, we'll just change the technical implementation a bit so no, this doesn't concern me.
