### ISSUE TITLE
Selecting multiple instances of one company is tricky

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#326]
![image](https://user-images.githubusercontent.com/2411066/31286901-e6c64a5a-aabf-11e7-9371-baa55c5a48ec.png)

If I want to select all the IBMs, there is no easy way for me to do that.

- the search is not specific to the selection already made (known issue that will be tackled, but relevant here too)
- there are no wild-cards
- there are only N instances being returned from the backend
- I cant easily select multiple instances from the dropdown without having to search anew
- already selected instances do not disappear from the search

Perhaps we should make the search contain a minimum of 3 characters and return N the matches from the backend with an option to return more?

@chutko I think this is a design problem too
@georgiana-b also a backend issue

**Comment by victor-nitu** [comment]
It's not much we can do with the current setup (drop down based). Longer list is not ideal IMHO.

Can we reimagine the whole company thing, maybe? But in such way that the query builder won't be too messed up?

**Comment by chutko** [comment]
related to #278
just different solution would be more suitable: suggestion search instead of select

**Comment by georgiana-b** [comment]
The backend already supports the equivalent of `ibm *` since it's an autocomplete but I have to remove the limit of 10 matches.

The main problem of UX seems to be that these matches are not automatically selected, you have to select each manually.
We could provide a way for the user to say: Ok, this is my search. Make a network of all companies returned by it.
For example we could show suggestions as you type and be able to choose actors one by one. But we can also add a button like "All matches" which can be pressed to stop suggestions and just make a network with all the matches. 

The problem with the above is that surely there will be some mismatches so there will be some nodes in the network that you don't want there and have to delete. 
Also, if you wanted to see all these IBMs as one node you would still have to cluster them in the network.

**Comment by chutko** [comment]
what we need is a searchable collection of companies and second collection which user can add his selected companies into. so user types something into a search field, matching companies display and you select them one by one (i suppose its not that much work, and we can also have button "add all") and add them to a collection which is displayed inside the search input. 

that is a definition of a multiple select with suggestion search. just the current solution seems not customizable enough for what we need it to do and display. so i would like to search for new solution with more options. lets not think about if it has materialize skin or not, we will make our own if it matches our needs in terms of functionality
i like something like this: https://selectize.github.io/selectize.js/

@nightsh what do you think?

by the way i am quite dissatisfied with availability of basic UX solutions for ember+materialize. maybe some day i will get pissed off and replace all materialize form inputs (or whole materialize) with bootstrap inputs (or bootstrap) and so many problems will dissapear.

**Comment by zufanka** [comment]
@georgiana-b shall we leave this issue for the future or is it doable until the end of december?

**Comment by chutko** [comment]
i think this can wait. it is one of smaller improvements which demands more research and analysis

**Comment by zufanka** [comment]
closed, new parent issue: https://github.com/tenders-exposed/elvis-ember/issues/434
