### ISSUE TITLE
Way too many contracts

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#330]
Why do these [two](http://ted.europa.eu/udl?uri=TED:NOTICE:108609-2013:TEXT:EN:HTML&src=0&tabId=1) [contracts](http://ted.europa.eu/udl?uri=TED:NOTICE:38399-2015:TEXT:EN:HTML&src=0&tabId=1) appear as 8 contracts [on the network](http://tenders.exposed/network/59dc84102dcb5613ab000001/suppliers)?

![image](https://user-images.githubusercontent.com/2411066/31377125-52f79474-ada7-11e7-90e9-b2b5fdfd93cb.png)

@georgiana-b @nightsh ?

**Comment by victor-nitu** [comment]
Pastes here the raw payload coming from the backend on this: http://paste.opensuse.org/view/raw/42161786

Noticeable is that they do have different IDs in the database. Passing the ball to @georgiana-b on this one.

**Comment by georgiana-b** [comment]
After further investigation I found that some contracts from the original OpenTed dataset appear multiple times.
For example [the one you discovered](http://ted.europa.eu/udl?uri=TED:NOTICE:38399-2015:TEXT:EN:HTML&src=0) just appears twice in the `eu_ted_contracts` table from old OpenTed database.

I considered a contract to a be unique combo of

- `doc_no`(e.g. 2015/S 023-038399)
- `lot_number`, 
- `contract_number`
- `operator_official_name`
- `contract_value`

`contract_value` was added because there are cases like [this messy tender](http://ted.europa.eu/udl?uri=TED:NOTICE:457546-2015:TEXT:EN:HTML&src=0) that don't include `contract_number` or `lot_number`. 
Although we will probably still have some false positives, I think this combo of fields is good enough at identifying a unique contract and thus delete extra occurrences.

For anyone interested I logged [in this CSV](https://storage.tenders.exposed/s/xaV04muPmoMzGsL) occurrences over 1 of duplicated combos.

**Comment by georgiana-b** [comment]
I removed all the duplicates and updated the indices. The networks were already made have not been regenerated and are still wrong so please make new networks.
Here is a [regenerated version](http://tenders.exposed/network/59e070872dcb562d81000002) of the [one you posted](http://tenders.exposed/network/59dc84102dcb5613ab000001).
