### ISSUE TITLE
Adjust designs inside network canvas

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#339]
i would like to refine visual of some things inside the network canvas.
if we zoom the network in, the labels and flags are all around the place as well the fonts are too huge. so i propose these changes:

1. set max font size to the labels and flags (from e.g. zoom 5, they will not increase in size) if possible
2. refine colors of the flags and labels (mainly transparent borders and backgrounds)

**Comment by chutko** [comment]
@nightsh you wanted to give me some hints about this

**Comment by victor-nitu** [comment]
There are several ways one can work on this.
The most straightforward way is to directly hack the `vis` package code inside `node_modules`. However, while this is simple to accomplish, it's dangerous to do so because you might easily lose your changes.
If you do this, any changes you make on the `vis` code would have to be pushed to the vis repo.

So you should probably: 
* clone the `vis` repo from here https://github.com/tenders-exposed/vis
* go inside the cloned project and run `npm link`
* in the `elvis-ember` project, remove `node_modules/vis` directory and run `npm install` to (hopefully) have it grabbed from your local copy instead, and not from github
* if all the above went well (you will see confirming messages), you can now proceed with hacking the `vis` code base
  * after each modification you make, you need to run `npm run build`
  * there is no need to reinstall the elvis-ember vis dependency on changes, but you might need to restart the ember server
  * the code you might be interested in is under `lib/network` path [link](https://github.com/tenders-exposed/vis/tree/master/lib/network)

LMK if I skipped anything.

**Comment by chutko** [comment]
it hurt badly, thanks to @nightsh's patience with making it running, i have adjusted fonts, paddings and borders of the network labels. looks less disturbing now. 

i have also turned off keyboard controls until #243 is solved
