### ISSUE TITLE
create buttons to opentender.eu from detailviews

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#403]
The buttons have to be pretty. @chutko do you have that desing somewhere still?

Link has to contain the country code + ID.
Both will be provided by the backend

Authority link format:
https://preview.opentender.eu/dk/authority/473650590266b8b9e3e6d8c87c81a432340b52b3455d476f0fae228667e6c0fe

Tender link format:
https://preview.opentender.eu/dk/tender/fffe3d07-a178-48f2-bf78-74d14ede0e4b

Company link format might be tricky to make, as according to @georgiana-b there is no such thing as company country.

Company link format:
https://preview.opentender.eu/dk/company/a80126e34e2f9e70facf2bbbb1a44b5a2956c799c4a398bc1491a2a384b1fdf1

**Comment by georgiana-b** [comment]
Here is a link to a company on OpenTender:

[`https://preview.opentender.eu/dk/company/694f39e8f516cb130fba94777ff0133bfda343530088128c0a340df6a9dd6ee1`](https://preview.opentender.eu/dk/company/694f39e8f516cb130fba94777ff0133bfda343530088128c0a340df6a9dd6ee1)

Notice the pattern is `http://host/country/company/id` so you always visualize the company within the context of a country. That's because on OpenTender you always choose a country first and then see everything from that country.

But of course a company can win contracts in multiple countries. On Elvis people can choose to see all the contracts of a company, from all the countries. So there will be multiple corresponding links to OpenTender for that company, one for each country.

We have to come up with a nice way to show  these multiple links for a company, ideally with the flag of each country on the link so that people can choose which OpenTender page to open.
