### ISSUE TITLE
Terminology updates

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-ember#409]
- [ ] It says “money flow” instead of “number of contracts” in node details (info box)
- [ ] Write “Select institutions/companies” instead of “Select companies” in the actor selection since we also show procurers

**Comment by georgiana-b** [comment]
@zufanka I also noticed in the actor details and relationship details template it says `Total income` which sounds off especially [for a relationship](https://tenders.exposed/network/5a92a0412dcb563c84000000/relationships/13986-1056903). I think calling it `Total money flow` would be better. WDYT?

**Comment by georgiana-b** [comment]
In the same actor details section, `Data Missing` is so vague even I can't figure what it means :smile: so it could really use a rename.

**Comment by zufanka** [comment]
@georgiana-b could you please attach screenshots? I am not sure what you are looking at, especially the second part :)

**Comment by georgiana-b** [comment]
![details_text_to_change](https://user-images.githubusercontent.com/8862002/36662531-5a9b32f0-1ae7-11e8-8333-aadcbf0242c3.png)

**Comment by zufanka** [comment]
is the above still relevant? :)

**Comment by georgiana-b** [comment]
No, but we have a new list for the new templates: 
c.c. @ca1yps0 

Contract (now tender) details:

- [x]  Rename `CONTRACT DETAILS` page to `TENDER DETAILS`
- [x] Populate tender details view with title, titleEnglish, description, price of tender
- [x] Replace `Award Date`  in tender details with tender year
- [x] Move  `Award Date` to lot details instead of  `Lot Reference Number`
- [x] Also remove `referenceNumber` from tender details
- [x] Rename `opented.eu` to `opentender.eu`
      - Link to `opentender.eu` should be of the form `https://opentender.eu/{tender.country}/tender/{tender.id}`
      - Link to `ted.europa.eu` should be of the form `http://ted.europa.eu/udl?uri=TED:NOTICE:{tender.TEDCNID_number}-{tender.TEDCNID_year}:TEXT:EN:HTML`. For example, for a `tender` with TEDCNID=2014/S 132-**237722**`  the url will be `http://ted.europa.eu/udl?uri=TED:NOTICE:237722-2014:TEXT:EN:HTML`. 
- [x] Change `Buyer` to `Buyers` because there can be more of them too
- [x] Remove `ENGLISH DESCRIPTION` from lot details

Actor details:

- [x] Add `Bids awarded` next to `All awarded amounts` 
- [x] In the `CONTRACTS` table of actor details show `tender title - lot title` in the `Contract` column
- [x] In company details replace `CONTRACTED GOVERNMENT INSTITUTIONS` with `CONTRACTING GOVERNMENT INSTITUTIONS`
- [x] Hide timeline

**Comment by georgiana-b** [comment]
@ca1yps0  Twitches:

- [x] Replace `N/A` with `?` or fruit  (for example [here](https://elvis-ember-new-backend.herokuapp.com/network/c7314864-a197-4857-bd2a-58dbefd3f775/buyers/b9f80b3b-e58b-40a2-9ecc-5ba12d53e879/b02380ff-660e-4454-a572-fb30f72a8c7a))
- [x] For the `Address of Implementation` section of lot details show:
     - (`rawAddres` || `street` ) + , +  `city` + , + `country` 
- [x] Split `tender.TEDCNID` by `/` to get the year and by `-` to get the notice number instead of relying on number of digits 
 - [ ] Fix permalinks for buyers, bidders and tenders. 
    For example when I open this link:
     [https://elvis-ember-new-backend.herokuapp.com/network/c7314864-a197-4857-bd2a-58dbefd3f775/buyers/b9f80b3b-e58b-40a2-9ecc-5ba12d53e879/b02380ff-660e-4454-a572-fb30f72a8c7a](https://elvis-ember-new-backend.herokuapp.com/network/c7314864-a197-4857-bd2a-58dbefd3f775/buyers/b9f80b3b-e58b-40a2-9ecc-5ba12d53e879/b02380ff-660e-4454-a572-fb30f72a8c7a) 
    it doesn't take me to that buyer but redirects me to 
    [https://elvis-ember-new-backend.herokuapp.com/network/c7314864-a197-4857-bd2a-58dbefd3f775/bidders](https://elvis-ember-new-backend.herokuapp.com/network/c7314864-a197-4857-bd2a-58dbefd3f775/bidders)
- [x] Remove country label from bidders (companies)
- [x] Use `country` from `tender` payload or from `buyer` payload to determine the country tag instead of the query.

**Comment by georgiana-b** [comment]
Moved the permalinks point into #422 because it doesn't have anything to do with terminology updates and it's an important issue in itself.
