### ISSUE TITLE
If company name is unknown, it does not appear on the network view

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#428]
![image](https://user-images.githubusercontent.com/2411066/37655875-b8154ca2-2c46-11e8-9b33-e01fca00735f.png)

Network : https://tenders.exposed/network/303c8277-79c0-4bd2-a964-afa3d89e9c06/buyers/f4ddbdf8-1203-409e-a21d-bc98b1e37053

Shouldn't we make it lead to a fruit node?

**Comment by georgiana-b** [comment]
This issue is not about bidders without `name`. It is about contracts for which bidders and sometimes even buyers are not disclosed as I explained in tenders-exposed/elvis-backend-node#61.

So, it's not that we have a bidder with `id` but no `name`, it's that we have no bidder records for a bid. We don't even know how many winners there were.

**Comment by georgiana-b** [comment]
Currently these bids are accounted for only in the nodes we do have. For example, if the data only discloses the buyer, it will appear in the network as an isolated node because there is no bidder to link it to.

In a call yesterday another idea was proposed: to show the missing actors as grey nodes. So, if we have a bid for which we don't know the bidder in the network we show the buyer(s) normally and the bidder(s) as a single grey node, connected by a normal edge.

**Comment by victor-nitu** [comment]
I think this was fixed. @ca1yps0 can you confirm and close if that's the case?

**Comment by zufanka** [comment]
@ca1yps0 was this fixed?
