### ISSUE TITLE
ALL AWARDED AMOUNTS does not add up

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#429]
![image](https://user-images.githubusercontent.com/2411066/37656663-f7391056-2c48-11e8-9a29-6203ff4fcf56.png)

![image](https://user-images.githubusercontent.com/2411066/37656727-29917930-2c49-11e8-9be6-2ad6acbf900c.png)

**Comment by georgiana-b** [comment]
@ca1yps0 From looking at one of these examples I noticed you are displaying the `finalValue` of the `tender` in the Contracts table instead of the `value` of the `bid`.

I'm sending you an array of `winning bids` (i.e. contracts) and if they have value it will appear in the field `value`. I'm also sending the `lot` and the `tender` the bid belongs to but that tender can have 23 other bids like this one. The `finalValue` of the `tender` is for all 24 bids. But in this table we are not displaying tenders, we are displaying winning bids, although it is a bit confusing with that `Bids` column there.

**Comment by zufanka** [comment]
@ca1yps0 @nightsh could you please review this?

**Comment by georgiana-b** [comment]
@calypso So to be more clear, to get the right value for `ALL AWARDED AMOUNTS` you have to sum up the `value` field in all the bids from `winning_bids` array.

**Comment by zufanka** [comment]
@ca1yps0 is this implemented?

**Comment by zufanka** [comment]
I think this is fixed, closing
