### ISSUE TITLE
[LEGEND] Make the carousel

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#447]
Implement the carousel in place of the legend on the loading screen

**Comment by zufanka** [comment]
Related: https://github.com/tenders-exposed/elvis-ember/issues/446

**Comment by chutko** [comment]
i see its on, but there are few small things which the carousel is missing:
1. the images within appear too small. use this code for images:
`<img src="..." width="690" height="330">`
(or specify the dimensions in css `width: 690px; height: 330px;`)
4. please use _Next_ and _Previous_ for the carousel buttons
5. when the loading is finished, _Close_ button needs to appear in the right bottom corner of the carousel
3. you probably havent touched network loading yet. when you do, make sure it works and looks like described in #446. also, loading is showing wrong progress, 40% should be just around the middle, right?
![network-loading](https://user-images.githubusercontent.com/4135015/44982501-65940000-af76-11e8-8fdb-3cb601dffa7a.png)
5. after the network is loaded, carousel should stay above the network canvas until the user closes it, because some networks load very fast (which is great)

**Comment by georgiana-b** [comment]
This is very much done and pretty I think.
Well done @chutko and @ca1yps0!

If it's all merged in master please close this.
