### ISSUE TITLE
flags in tender details are wrong

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-ember#469]
If I select multiple countries on the query builder, all of them appear in the country from which the tender comes. This is not accurate. It should take the value out of _tender_country_ in the API

![image](https://user-images.githubusercontent.com/2411066/50446476-61b92e80-0915-11e9-80bb-fe68605c3aa9.png)

UPDATE
We don't have a tender details anymore, but it's an issue in the government details page too
![image](https://user-images.githubusercontent.com/2411066/77850251-7992f880-71d1-11ea-9916-20a87fc8601b.png)

**Comment by zufanka** [comment]
@nightsh @georgiana-b what is the status of this??

**Comment by zufanka** [comment]
@nightsh @ca1yps0 fix pls?

**Comment by georgiana-b** [comment]
So we just need to display:
- for bidder the country that you get in the `bidder.country` object:
![image](https://user-images.githubusercontent.com/8862002/77850497-346fc600-71d3-11ea-8975-ff10e7253b0b.png)
- for buyer the country of the tender (the value of `tender.country` object)

**Comment by georgiana-b** [comment]
Sorry guys, you shouldn't be digging for the country all the way into the bidder/buyer objects. 

I'm going to add a new `country` attribute to nodes and `countries` to clusters where I will send the country of the original bidder or bidders in the case of a cluster.

**Comment by georgiana-b** [comment]
Opened https://github.com/georgiana-b/defense-elvis-backend/issues/14 about it. I'll keep you posted

**Comment by georgiana-b** [comment]
This issue has been fixed in https://github.com/georgiana-b/defense-elvis-backend/issues/14.

You will now find a new attribute `countries` in node details and cluster details that is an array of country codes of the bidder/buyer in question.

![image](https://user-images.githubusercontent.com/8862002/82656075-69245a80-9c23-11ea-92c9-dd575a9f0885.png)

❗ In the case of manual data, this array will always be empty because we don't know the actors address so make sure you also cover that case.
